
import { MainHeader } from '@/components/header'
import '../globals.css'

import '@/assets/scss/kodchallenge.scss'
import { cn } from '@/lib/utils'
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      <div className={cn("dot-points", "full-screen")}></div>
      <main className='my-32'>
        <div className="container">
          <div className="flex flex-col items-center justify-center space-y-4">
            {children}
          </div>
        </div>
      </main>
    </>
  )
}
