
import './globals.css'

import '@/assets/scss/kodchallenge.scss'
import KcProviders from './_providers'
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
import 'moment/locale/tr'
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='light'>
      <body className='font-nunito text-base'>
        <KcProviders>
          {children}
        </KcProviders>
      </body>
    </html>
  )
}
